num1 = int(input("Número 1: "))
num2 = int(input("Número 2: "))
print("La suma de los dos números es: ")
print(num1 + num2)
print("La resta de los dos números es: ")
print(num1 - num2)
print("La multiplicación de los dos números es: ")
print(num1 * num2)
print("La división de los dos números es: ")
print(num1 / num2)